export default {
  comics: [
    {
      name: "The End",
      sortname: "End, The",
      rssurl: "https://feeds.feedburner.com/endcomic/QkZz",
      archiveurl: "http://www.endcomic.com/archives/",
      thumb: "hubbox_THE_END.png",
      genres: ["action-adventure", "lgbt", "sci-fi"],
    },
    {
      name: "Ghost Junk Sickness",
      rssurl: "https://www.ghostjunksickness.com/comic/rss",
      archiveurl: "https://www.ghostjunksickness.com/comic/archive",
      thumb: "hubbox_GJS.png",
      genres: ["action-adventure", "lgbt", "sci-fi"],
    },
    {
      name: "The Automan’s Daughter",
      sortname: "Automan’s Daughter, The",
      rssurl: "https://www.automansdaughter.com/comic/rss",
      archiveurl: "https://www.automansdaughter.com/comic/archive",
      thumb: "hubbox_THE_AUTOMANS DAUGHTER.png",
      genres: ["action-adventure", "sci-fi", "steampunk"],
    },
    {
      name: "Magical How?",
      rssurl: "https://www.magicalhowcomic.com/comic/rss",
      archiveurl: "https://www.magicalhowcomic.com/comic/archive",
      thumb: "hubbox_MAGICAL_HOW.png",
      genres: ["fantasy", "lgbt"],
    },
    {
      name: "Phantomarine",
      rssurl: "https://www.phantomarine.com/comic/rss",
      archiveurl: "https://www.phantomarine.com/comic/archive",
      thumb: "hubbox_PHANTOMARINE.png",
      genres: ["action-adventure", "mystery"],
    },
    {
      name: "Hazy London",
      rssurl: "https://www.hazylondon.com/comic/rss",
      archiveurl: "https://www.hazylondon.com/comic/archive",
      thumb: "hubbox_HAZY.png",
      genres: ["action-adventure", ],
    },
    {
      name: "Fairmeadow",
      rssurl: "https://www.fairmeadowcomic.com/comic/rss",
      archiveurl: "https://www.fairmeadowcomic.com/comic/archive",
      thumb: "hubbox_FAIRMEADOW.png",
      genres: ["action-adventure", "drama", "fantasy", "lgbt"],
    },
    {
      name: "Tigress Queen",
      rssurl: "https://www.tigressqueen.com/comic/rss",
      archiveurl: "https://www.tigressqueen.com/comic/archive",
      thumb: "hubbox_TIGRESS_QUEEN.png",
      genres: ["action-adventure", "fantasy", "romance"],
    },
    {
      name: "Godslave",
      sortname: "Godslave",
      rssurl: "https://www.godslavecomic.com/comic/rss",
      archiveurl: "https://www.godslavecomic.com/comic/archive",
      thumb: "hubbox_GODSLAVE.png",
      genres: ["action-adventure", "fairytale", "fantasy", "urban-fantasy"],
    },
    {
      name: "White Noise",
      sortname: "White Noise",
      rssurl: "http://www.white-noise-comic.com/comic/rss",
      archiveurl: "https://www.white-noise-comic.com/comic/archive",
      thumb: "hubbox_WHITENOISE.png",
      genres: ["action-adventure", "lgbt", "slice-of-life"],
    },
    {
      name: "Bicycle Boy",
      rssurl: "https://www.bicycleboy.net/comic/rss",
      archiveurl: "https://www.bicycleboy.net/comic/archive",
      thumb: "hubbox_BICYCLE_BOY.png",
      genres: ["action-adventure", "dystopian", "sci-fi"],
    },
    {
      name: "The Otherknown",
      sortname: "Otherknown, The",
      rssurl: "https://www.otherknown.com/comic/rss",
      archiveurl: "https://www.otherknown.com/comic/archive",
      thumb: "hubbox_OTHERKNOWN.png",
      genres: ["action-adventure", "drama", "sci-fi"],
    },
    {
      name: "Heroes of Thantopolis",
      rssurl: "https://www.heroesofthantopolis.com/comic/rss",
      archiveurl: "https://www.heroesofthantopolis.com/comic/archive",
      thumb: "hubbox_HEROES_OF THANTOPOLIS.png",
      genres: ["action-adventure", "fantasy", "lgbt"],
    },
    {
      name: "Daughter of the Lilies",
      rssurl: "https://www.daughterofthelilies.com/dotl/rss",
      archiveurl: "https://www.daughterofthelilies.com/comic/archive",
      thumb: "hubbox_DOTL.png",
      genres: ["action-adventure", "fantasy"],
    },
    {
      name: "Lies Within",
      rssurl: "https://www.lieswithincomic.com/comic/rss",
      archiveurl: "https://www.lieswithincomic.com/comic/archive",
      thumb: "hubbox_LIES_WITHIN.png",
      genres: ["action-adventure", "drama", "lgbt", "urban-fantasy"],
    },
    {
      name: "In Blood We Rise",
      rssurl: "https://inbloodwerise.com/comic/rss",
      archiveurl: "https://inbloodwerise.com/comic/archive",
      thumb: "hubbox_INBLOOD.png",
      genres: ["action-adventure", "fantasy", "historical-fiction", "romance"],
    },
    {
      name: "Solstoria",
      rssurl: "https://solstoria.net/comic/rss",
      archiveurl: "https://solstoria.net/comic/archive",
      thumb: "hubbox_SOLSTORIA.png",
      genres: ["action-adventure", "fantasy"],
    },
    {
      name: "Starhammer",
      rssurl: "https://www.starhammercomic.com/rss.php",
      archiveurl: "https://www.starhammercomic.com/comic/archive",
      thumb: "hubbox_STARHAMMER.png",
      genres: ["action-adventure", "slice-of-life", "superhero"],
    },
    {
      name: "Ozzie the Vampire",
      rssurl: "https://www.ozziethevampire.com/comic/rss",
      archiveurl: "https://www.ozziethevampire.com/comic/archive",
      thumb: "hubbox_OZZIEVAMP.png",
      genres: ["action-adventure", "comedy"],
    },
    {
      name: "Tiger, Tiger",
      rssurl: "https://www.tigertigercomic.com/tiger-tiger/rss",
      archiveurl: "https://www.tigertigercomic.com/comic/archive",
      thumb: "hubbox_TIGERTIGER.png",
      genres: ["action-adventure", "historical-fiction", "mystery"],
    },
  ],
};
